### ISSUE TITLE
Encoding error: KeyError: 'UNK'

### ISSUE THREAD

**Issue by manishprasadthapliyal** [jatana-research/email-summarization#1]
Am facing issue in encode function of skipthought.py
Below line has thrown error:
uembedding[j,ind] = model['utable']['UNK']

KeyError: 'UNK'

am using below package version:
Theano== 0.7.0
numpy==1.15.1
keras== 2.2.2
python==2.7.15

![image002](https://user-images.githubusercontent.com/12188535/45862463-7f637e80-bd8f-11e8-95ab-abdbc8bd8547.png)

**Comment by kushalchauhan98** [comment]
Can you check the md5sum of dictionary.txt for me? It should be - 26d8a3e6458500013723b380a4b4b55e.

**Comment by manishprasadthapliyal** [comment]
After running the command
md5sum dictionary.txt  
output:
706989577b08ba1988437313e8e7b656  dictionary.txt

**Comment by kushalchauhan98** [comment]
Can you redownload the file? The file you have is corrupted.

**Comment by manishprasadthapliyal** [comment]
Thanks, I have re-downloaded the file and checksum is same. I will be testing again if any issue i will come back.

**Comment by kushalchauhan98** [comment]
Also, check the MD5 hashes for the other files too and check if they are the same as:

9a15429d694a0e035f9ee1efcb1406f3  bi_skip.npz
c9b86840e1dedb05837735d8bf94cee2  bi_skip.npz.pkl
022b5b15f53a84c785e3153a2c383df6  btable.npy
26d8a3e6458500013723b380a4b4b55e  dictionary.txt
8eb7c6948001740c3111d71a2fa446c1  uni_skip.npz
e1a0ead377877ff3ea5388bb11cfe8d7  uni_skip.npz.pkl
5871cc62fc01b79788c79c219b175617  utable.npy

**Comment by kushalchauhan98** [comment]
Please notify if your problem is resolved.

**Comment by manishprasadthapliyal** [comment]
Thanks, Kushal it is working now :)
